// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.user_id", "3fa20d55-37ee-4f7a-9601-2e2ddda8dce5");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1547734394);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1547734514);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1547737514);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1547734154);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1547734034);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1547734274);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1547734754);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1547734634);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.lastDir", "/home/osboxes/Documents");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1541695962);
user_pref("browser.laterrun.bookkeeping.sessionCount", 6);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ea5b24ea-1f42-4143-b21f-b79df062f4b0}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1541653200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.finished", true);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1541697188);
user_pref("browser.onboarding.notification.tour-ids-queue", "");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.state", "watermark");
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1547739357789");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1547741139789");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1547737455294");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1547741055294");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181023214907");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1547733885");
user_pref("browser.slowStartup.averageTime", 2863);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20181023214907");
user_pref("browser.startup.homepage_override.mstone", "63.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1541695967713");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "7947403aad6d4542afe9e1a9941f0e4b");
user_pref("extensions.blocklist.lastModified", "Wed, 16 Jan 2019 17:13:48 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1547734395);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181023214907");
user_pref("extensions.lastAppVersion", "63.0");
user_pref("extensions.lastPlatformVersion", "63.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{bf719702-421a-4128-8879-f6fd04ea157d}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"390f64df-e8aa-4dcd-8f43-911ca4472055\",\"webcompat@mozilla.org\":\"e1d702a3-0d6f-4877-a1c1-4a3732f34ed5\",\"screenshots@mozilla.org\":\"1595b21c-b4c0-4b26-acd9-7f3706390502\",\"fxmonitor@mozilla.org\":\"e783bbd9-acda-44bd-aa0c-4c53eee4ff26\"}");
user_pref("idle.lastDailyNotification", 1547734337);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1547734022);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181023214907");
user_pref("media.gmp-manager.lastCheck", 1547734021);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1547734337);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "db0288f5-93ed-4ed5-b8cb-4410b3c33091");
user_pref("services.blocklist.addons.checked", 1547734230);
user_pref("services.blocklist.gfx.checked", 1547734230);
user_pref("services.blocklist.onecrl.checked", 1547734230);
user_pref("services.blocklist.pinning.checked", 1547734230);
user_pref("services.blocklist.plugins.checked", 1547734230);
user_pref("services.settings.clock_skew_seconds", -144);
user_pref("services.settings.last_etag", "\"1547658828472\"");
user_pref("services.settings.last_update_seconds", 1547734417);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1547734337);
user_pref("toolkit.startup.last_success", 1547733883);
user_pref("toolkit.telemetry.cachedClientID", "af859dff-19da-41b2-af66-f9c003f58da0");
user_pref("toolkit.telemetry.previousBuildID", "20181023214907");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
